packages = ["numpy", "gmpy2", "ssl", "pyee", "mpyc-0.8.8-py3-none-any.whl"]
# packages = ["numpy", "gmpy2", "ssl", "aiortc"]
# xterm = true

# plugins = ["py-terminal.py"]
# plugins = ["py-term.js"]
# plugins = ["py-term.py"]
[[fetch]]
from = "./py/"
to_folder = "./"
files = ["secretsanta.py", "logging_setup.py"]

[[fetch]]
from = "./py/mpycweb"
to_folder = "./mpycweb"
files = [
    "__init__.py",
    "debug.py",
    "peerjs.py",
    "state.py",
    "transport.py",
    "worker.py"
]
